### ISSUE TITLE
how to write a maths function in thingml and pass the function result into parameter

### ISSUE THREAD

**Issue by FeltonXuAtECNU** [HEADS-project/training#101]
I'm trying to write a maths function which could generation some kind of distribution, but I don't how to do that in ThingML because there's no example to follow (to write in JAVA or C++ or ...). I Also, I don't how to pass the result of that maths function to the message construction like "sendPort!indoorTemp(5) " . 5 here should be replaced by the result of function.

Could you help me with that syntax in ThingML. Thanks!

**Comment by brice-morin** [comment]
See https://github.com/HEADS-project/training/blob/master/5.ThingML_CEP/5.Windows/Windows.thingml#L26 for an example of a function. You can just call a function from within a message.

**Comment by FeltonXuAtECNU** [comment]
Actually, I mean, if I want to use some existing maths library either in Java or C++, can I do that? What should I do?

**Comment by brice-morin** [comment]
Tutorial 1 e.g. shows how to mix ThingML and Java code. Same applies to you math libs in Java. See https://github.com/HEADS-project/training/blob/master/1.ThingML_Basics/4.Timers/_java/JavaTimer.thingml.

You can store results of Java functions in a thingml variable and then pass it to your message. 

1 / Do the tutorials, they typically contain the answer (are good hints) to your question
2/ Start doing something in ThingML, it will be easier for us to help you fixing some ThingML than providing general support.
