### ISSUE TITLE
keep if does not work always correct 

### ISSUE THREAD

**Issue by omidkhodatars** [HEADS-project/training#106]
I have made little changes to the original code but this faced error when i ran it with java :

 stream filteredMergeFail
    from   e1 : cep?m2::keep if not e1.b 
    select var a : Boolean = e1.b 
    produce cep!res2(a)

![error-keepif-heads-java-png](https://cloud.githubusercontent.com/assets/7591138/14885974/a1ea45cc-0d4e-11e6-9964-6c347aee613d.JPG)

**Comment by brice-morin** [comment]
Did you update your ThingML plugins to the latest version? We did quite some fixes on the CEP in Java and JS this week. If yes, I will look into more details and create a test case for that.

**Comment by omidkhodatars** [comment]
it is fixed now , thanks
