### ISSUE TITLE
'keep if' - different output by Java and JavaScript

### ISSUE THREAD

**Issue by omidkhodatars** [HEADS-project/training#107]
i have tested the provided example for 'keep if' syntax , the output result  by Java and JavaScript are totally different . 

output by Java :  
![output](https://cloud.githubusercontent.com/assets/7591138/14886386/d9958048-0d50-11e6-9cee-ad157c87141c.JPG)

output by JavaScript : 
![outputjavascript](https://cloud.githubusercontent.com/assets/7591138/14886392/e70ef75e-0d50-11e6-9184-292c78b4437d.JPG)

**Comment by brice-morin** [comment]
I had this same issue, but AFAIK, it is fixed now. Are you sure you updated your plugins?

**Comment by omidkhodatars** [comment]
Thanks , i updated my plugin and it is solved
