### ISSUE TITLE
How to maniplate ThingML models

### ISSUE THREAD

**Issue by Georgia88** [HEADS-project/training#109]
I was reading an article on https://github.com/HEADS-project/training/issues/95 and found something interesting. 

However, when I wanted to follow the instruction you guys provided, the website https://github.com/HEADS-project/training/tree/master/1.ThingML_Basics/7.%20ReadThingMLModel doesn't work any more...Could any of you send me a new site on how to do that?  

Any help or suggestion will be appreciated.

Georgia

**Comment by brice-morin** [comment]
https://github.com/HEADS-project/training/tree/79d92e02eaee41a548dd7ee3448ccc6b9642cc6e/1.ThingML_Basics/7.ReadThingMLModel

**Comment by Georgia88** [comment]
But is there any document on the API you guys provided? For example, how can extract every field in ThingML? Like transition, event...

**Comment by brice-morin** [comment]
You can browse ThingML model in the same way you can browse any EMF-based models. I recommend you to first get use to the Eclipse Modeling Framework. Note that we also provide [a set of helpers](https://github.com/SINTEF-9012/ThingML/tree/master/org.thingml.model/src/main/java/org/sintef/thingml/helpers) to extract fields more easily.
