### ISSUE TITLE
How to import kevoree-js project into HEADS IDE?

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/training#11]
It seems from the tutorial text (https://github.com/HEADS-project/training/tree/master/2.Kevoree_Basics/1.HelloWorld/js) that I should be able to work with kevoree js project in HEADS IDE, but I it is not described (I think) how this project is imported.

**Comment by maxleiko** [comment]
The [0.General features of the HEADS IDE](https://github.com/HEADS-project/training/tree/master/2.Kevoree_Basics) are what you are looking for, no ?

**Comment by brice-morin** [comment]
@kehusa : if that information is sufficient, please close the issue. Or else elaborate more on your problem.

**Comment by kehusa** [comment]
I will do, when I have tested it ;-)



2015-01-06 9:38 GMT+01:00 Brice Morin <notifications@github.com>:

> @kehusa <https://github.com/kehusa> : if that information is sufficient,
> please close the issue. Or else elaborate more on your problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEADS-project/training/issues/11#issuecomment-68839367>
> .
>



-- 
Knut Eilif Husa

Tellu AS
Email: knut.eilif.husa@tellu.no
Mob: (+47) 452 49496
Web: www.tellu.no

**Comment by kehusa** [comment]
I do not see the "Kevoree JS Project" option in my  "New Project" dialogue:

[image: Innebygd bilde 1]

2015-01-06 9:40 GMT+01:00 Knut Eilif Husa <knut.eilif.husa@tellu.no>:

> I will do, when I have tested it ;-)
>
>
>
> 2015-01-06 9:38 GMT+01:00 Brice Morin <notifications@github.com>:
>
>> @kehusa <https://github.com/kehusa> : if that information is sufficient,
>> please close the issue. Or else elaborate more on your problem.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/HEADS-project/training/issues/11#issuecomment-68839367>
>> .
>>
>
>
>
> --
> Knut Eilif Husa
>
> Tellu AS
> Email: knut.eilif.husa@tellu.no
> Mob: (+47) 452 49496
> Web: www.tellu.no
>
>


-- 
Knut Eilif Husa

Tellu AS
Email: knut.eilif.husa@tellu.no
Mob: (+47) 452 49496
Web: www.tellu.no
