### ISSUE TITLE
http://dist.thingml.org/update doesn't work here

### ISSUE THREAD

**Issue by FeltonXu** [HEADS-project/training#111]
When I tried to install new software (i.e., the plugin for ThingML), I cannot retrieve resource on http://dist.thingml.org/update. I can't figure out the reason. The website worked before. Now I have to reinstall ThingML plugin because I reinstalled the windows system.

Can you help me to fix that problem?

Thanks in advance!

**Comment by brice-morin** [comment]
Well... Clicking on the link obviously work. Start from a HEADS IDE (links on this repo), add the ThingML update site and update/install ThingML
