### ISSUE TITLE
Failing compile of old code - New syntax for network plugins?

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/training#112]
The following configuration fails to compile
indicating error at the end of the keyword "over" 

import "../Timer.thingml"

configuration TestTimerRcd {
    instance client0 : ActiveTimer//this is your application
    set client0.period = 1000
    set client0.name = "A1 1000\n"
    connector client0.timer **over** Rcdtimer0    
    instance client1 : ActiveTimer//this is your application
    set client1.period = 1500
    set client1.name = "        A2 1500\n"
    connector client1.timer **over** Rcdtimer1    
    instance client2a : ActiveTimer//this is your application
    set client2a.period = 10000
    set client2a.name = "                A3 10000\n"
    connector client2a.timer **over** Rcdtimer2    
    instance client2p : PassiveTimer//this is your application
    set client2p.name = "                        P3 10000\n"
    connector client2p.timer **over** Rcdtimer2    
}

C:\fw\heads-rcdG\thingml\4.Timers\_rcd>java -cp .;c:\javasrc\ThingML-fork-9032\compilers\re
.jar;C:\javasrc\ThingML-fork-9032\compilers\official-network-plugins\target\official-networ
-c sintefboard -s RcdTimer.thingml -o genrcdtimer
Running ThingML -c sintefboard -s RcdTimer.thingml -o genrcdtimer
Checking for EMF errors and warnings
ERROR: The input model contains 4 errors.
Syntax error in file file:/C:/fw/heads-rcdG/thingml/4.Timers/_rcd/RcdTimer.thingml (18, 34)
Syntax error in file file:/C:/fw/heads-rcdG/thingml/4.Timers/_rcd/RcdTimer.thingml (15, 34)
Syntax error in file file:/C:/fw/heads-rcdG/thingml/4.Timers/_rcd/RcdTimer.thingml (11, 33)
Syntax error in file file:/C:/fw/heads-rcdG/thingml/4.Timers/_rcd/RcdTimer.thingml (7, 33)
Checking for EMF errors and warnings
ERROR: The input model contains errors.

C:\fw\heads-rcdG\thingml\4.Timers\_rcd>

**Comment by Lyadis** [comment]
No, the syntax hasn't changed. Can you edit your cexample to add protocols declaration?

**Comment by sdalgard** [comment]
Problem fixed when adding protocol declaration
Thank you :-)
