### ISSUE TITLE
Issues when manipulating ThingML

### ISSUE THREAD

**Issue by jobs10000** [HEADS-project/training#118]
When I was running the project provided at https://github.com/HEADS-project/training/tree/79d92e02eaee41a548dd7ee3448ccc6b9642cc6e/1.ThingML_Basics/7.ReadThingMLModel, I encountered the following problem.

Loading input file: C:\GenerateThingML\models\Basics\Timer\PingPong.thingml...
org/antlr/runtime3_4_0/Lexer
java.lang.NoClassDefFoundError: org/antlr/runtime3_4_0/Lexer
	at org.sintef.thingml.resource.thingml.mopp.ThingmlResource.<init>(ThingmlResource.java:166)
	at org.sintef.thingml.resource.thingml.mopp.ThingmlResourceFactory.createResource(ThingmlResourceFactory.java:25)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(ResourceSetImpl.java:425)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.createResource(ResourceSetImpl.java:414)
	at ReadThingML.main(ReadThingML.java:33)
Caused by: java.lang.ClassNotFoundException: org.antlr.runtime3_4_0.Lexer
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 5 more

I didn't use maven here (because I have to build my own project from scratch), but I have included all the jar file needed (including org.sintef.thingml.resource.thingml_0.7.0.201612211920.jar and org.sintef.thingml.model_0.7.0.201612211920 .jar in my project.

Do you have any idea how to fix that problem? 

Platform: Windows 10 & Eclipse

**Comment by brice-morin** [comment]
You probably forgot to include the JAR file for ANTLR 3.4.0, since a class belonging to ANTLR cannot be found.

**Comment by jobs10000** [comment]
It still doesn't work. The following is a snapshot of my project. I guess, the jar does not matter, right?




Do you have idea how to save ThingML as XML instead of using meta model? 


At 2016-12-23 03:34:14, "Brice Morin" <notifications@github.com> wrote:


You probably forgot to include the JAR file for ANTLR 3.4.0, since a class belonging to ANTLR cannot be found.

**Comment by jobs10000** [comment]
![issue](https://cloud.githubusercontent.com/assets/24716466/21448587/72578972-c91f-11e6-85df-975b8b0a1405.png)

This link is a screenshot of my eclipse project.

**Comment by brice-morin** [comment]
This [JAR](http://thingml.org/dist/ThingMLCLI.jar) contains all dependencies.

Also, all the helper function, such as `allStates` or `allThings` have been changed. Look in [those files](https://github.com/SINTEF-9012/ThingML/tree/master/org.thingml.model/src/main/java/org/sintef/thingml/helpers)

**Comment by jobs10000** [comment]
Would you mind giving a little more explanation on how to work on that (extracting ThingML elements)? What is ThingMLElement self, Configuration self and etc? What kind of parameter am I supposed to pass? If possible, could you please rewrite the program provided at here https://github.com/HEADS-project/training/tree/79d92e02eaee41a548dd7ee3448ccc6b9642cc6e/1.ThingML_Basics/7.ReadThingMLModel? I am really interested in working on that, because someone here at my university has published a paper on that? Thanks a lot!
