### ISSUE TITLE
configure Java package name

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#120]
When I generate from ThingML tutorial example training\1.ThingML_Basics\2.PingPong\PingPong.thingml
I get
`package org.thingml.generated.api;

public interface AttributeListener {
    void onUpdate(String instance, String attribute, Object newValue);
}
` in a file thingml-gen\java\PingPongCfg\src\main\java\com\softwareag\research\heads\api\AttributeListener.java. Thus, the Java package and the folder do not match.

Where can I configure the Java Package name?
The Eclipse project is from the current GitHub training repository.

ThingML plugins: version 1.0.0.201704280847
Kevoree plugins: version 5.4.0

**Comment by brice-morin** [comment]
Yes, that features has not been fully implemented. The safest is to use org.thingml.generated in the ThingML preferences and then use IDE's features if you want to rename packages, etc. I suspect that you at some point put com.softwareag.research.heads in the ThingML preference menu. We will try to fix that in ThingML v2.

**Comment by skorsky** [comment]
The ThingML preferences was the helpful hint! Thanks.
