### ISSUE TITLE
In exercise 5 (Kevoree tutorial), cannot start node.js node with start model

### ISSUE THREAD

**Issue by brice-morin** [HEADS-project/training#16]
```
11:04:05  ALL    KevoreeLogger    Set logLevel= info
11:04:05  INFO   KevoreeCore      Platform node name: jsNode
11:04:05  ERROR  NodeJSRuntime    Unable to load Kevoree KevScript: parse error:
 failed to match 'ws' at line=12, col=0, pos=331
11:04:05  ERROR  NodeJSRuntime    Platform shut down.
```

**Comment by maxleiko** [comment]
From the directory, I've just run that

```sh
kevoreejs -n jsNode --kevscript=starterModel.kevs
```

and it worked.  Are you on Windows ? Are you sure the path is the right one ?

**Comment by brice-morin** [comment]
Yes, I am on windows... when the path is wrong, I get another error... So I assume it is right... But it will run kevoreejs directly in the folder where the model is... I guess that it safer

**Comment by brice-morin** [comment]
Same problem...

**Comment by maxleiko** [comment]
Looks like a typo in the KevScript you've selected.
