### ISSUE TITLE
Compilation error when compiling TestTimerC (in cygwin)

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/training#2]
KnutEilif@KnutEilif-PC /cygdrive/c/Users/KnutEilif/HeadsIde/workspace/Tutorial/thingml-gen/posix/TestTimerC
$ make
cc -O2 -w -c ClockLinux.c
ClockLinux.c: In function ‘f_ClockLinux_sleep_ms’:
ClockLinux.c:29:16: error: storage size of ‘tv’ isn’t known
 struct timeval tv;
                ^
Makefile:10: recipe for target 'ClockLinux.o' failed
make: *** [ClockLinux.o] Error 1

**Comment by brice-morin** [comment]
The C compiler first targets proper platforms (Linux and micro-controllers). It was a bit ambitious to target Windows directly with this compiler, even through CygWin. I suggest we close that issue, unless it is blocking for anyone (who can reopen it).
