### ISSUE TITLE
Unable to generate kevoree  

### ISSUE THREAD

**Issue by junaidSoftwareAG** [HEADS-project/training#21]
Hi ,

When i try to run the below command 
npm i -g generator-kevoree

Output:
npm WARN excluding symbolic link test\symlinks\dir1\dangling-symlink -> does-not
-exist
C:\Users\jumo\AppData\Roaming\npm\generator -> C:\Users\jumo\AppData\Roaming\npm
\node_modules\generator\bin\index.js
C:\Users\jumo\AppData\Roaming\npm\generate -> C:\Users\jumo\AppData\Roaming\npm\
node_modules\generator\bin\index.js
generator@1.0.1 C:\Users\jumo\AppData\Roaming\npm\node_modules\generator
├── colors@0.6.2
├── async@0.2.10
├── fs-extra@0.6.4 (jsonfile@1.0.1, rimraf@2.2.8, mkdirp@0.3.5, ncp@0.4.2)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── replace@0.2.10 (colors@0.5.1, minimatch@0.2.14, nomnom@1.6.2)
├── prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.5, winston@0.8.3,
utile@0.2.1)
└── findit@0.1.2 (seq@0.3.5)

but when i try to  ask Yeoman to generate the architecture of your Kevoree JS project using command it will show that the generator is not created 
yo kevoree

Output :
You don't seem to have a generator with the name kevoree installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 0 registered generators run yo with the `--help` option.

**Comment by junaidSoftwareAG** [comment]
Issue resolved i places extra space in the command
npm i -g generator -kevoree

**Comment by maxleiko** [comment]
If you put a space between `generator` and `-kevoree` it won't install what you want.

**Comment by maxleiko** [comment]
`generator-kevoree` with **no** spaces, is the name of an `npm` module that let's you scaffold Kevoree projects using `Yeoman`
