### ISSUE TITLE
Want to import Kevoree helloworld project form Git repository

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#24]
I use Egit and the Git perspective to import projects.
This does not work for the Kevoree helloworld project (Java). The .project file is missing. Sreenshot attached.

![git import projects](https://cloud.githubusercontent.com/assets/8928699/5630536/064b9b3c-95bf-11e4-8161-fe451151815c.png)

**Comment by brice-morin** [comment]
I would recommend importing the separate Java folders as Maven projects

**Comment by maxleiko** [comment]
@brice-morin gave the answer :+1:
