### ISSUE TITLE
Missing Builder on Kevoree project

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#25]
If I look at the Builders for the Kevoree helloworld project, the Kevoree builder is missing.
I've installed the KevoreeEclipsePluginFeature 5.1.4 (KevoreeEclipsePluginFeature.feature.group, Kevoree Team). See screenshot: 
![missing builder](https://cloud.githubusercontent.com/assets/8928699/5630647/ebe6b38e-95bf-11e4-93d6-4f0c95764c3e.png)

**Comment by maxleiko** [comment]
The Kevoree builder is deprecated/obsolete now. We only use Maven now.

**Comment by brice-morin** [comment]
@barais : Then this deprecated builder should be removed from HEADS IDE
