### ISSUE TITLE
No metadata file found for org.kevoree.sample/helloworld/0.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#26]
I used 'mvn install' to build the Kevoree helloworld project and then 'mvn kev:run' to run it.

In the console I get
00:05 ERROR: No metadata file found for org.kevoree.sample/helloworld/0.0.1-SNAPSHOT
and 
00:05 ERROR: Unable to resolve /packages[org]/packages[kevoree]/packages[sample]/deployUnits[hashcode=,name=helloworld,version=0.0.1-SNAPSHOT]

Complete log (Windows 7 cmd):
D:\Users\mask\git\HEADS\training\2.Kevoree_Basics\1.HelloWorld\java>mvn kev:run
[INFO] Scanning for projects...
[INFO]
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Kevoree :: helloworld 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- org.kevoree.tools.mavenplugin:5.1.4:run (default-cli) @ helloworld ---
00:00 INFO: Bootstrap Kevoree node : node0, version 5.1.4
00:02 INFO: Resolved 25 typeDefinitions from Kevoree Registry http://registry.kevoree.org/v5/ (JavaNode/5.2.0,JavaNode/5.1.1,JavaNode/5.0.3,JavaNode/5.2.1,JavaNode/5.1.2,JavaNode/5.2.2,JavaNode/5.1.3,
JavaNode/5.0.4,JavaNode/5.0.5,JavaNode/5.0.6,JavaNode/5.0.6-SNAPSHOT,JavaNode/5.0.7,JavaNode/5.1.4-SNAPSHOT,JavaNode/5.2.2-SNAPSHOT,JavaNode/5.2.1-SNAPSHOT,JavaNode/5.0.8-SNAPSHOT,JavaNode/5.1.1-SNAPS
HOT,JavaNode/5.0.3-SNAPSHOT,JavaNode/5.1.2-SNAPSHOT,JavaNode/5.0.5-SNAPSHOT,JavaNode/5.0.4-SNAPSHOT,JavaNode/5.2.3-SNAPSHOT,JavaNode/5.1.0,JavaNode/5.0.7-SNAPSHOT,HelloWorld/0.0.1-SNAPSHOT)
00:02 WARN: Try to select snapshot in best effort mode for org.kevoree.example.HelloWorld
00:02 INFO: Resolving ............. /packages[org]/packages[kevoree]/packages[library]/packages[java]/deployUnits[hashcode=,name=org.kevoree.library.java.javaNode,version=5.2.2]
00:03 INFO: Resolved in 128ms
00:03 INFO: JavaNode, changing LOG level to INFO
00:03 INFO: Starting node type of node0
00:03 INFO: Resolving ............. /packages[org]/packages[kevoree]/packages[sample]/deployUnits[hashcode=,name=helloworld,version=0.0.1-SNAPSHOT]
00:05 ERROR: No metadata file found for org.kevoree.sample/helloworld/0.0.1-SNAPSHOT
00:05 INFO: Resolved in 2122ms
00:05 ERROR: Unable to resolve /packages[org]/packages[kevoree]/packages[sample]/deployUnits[hashcode=,name=helloworld,version=0.0.1-SNAPSHOT]
00:05 WARN: Error during execution of AddDeployUnit org.kevoree.sample/helloworld/0.0.1-SNAPSHOT/
00:05 WARN: JavaSENode is aborting last update...
00:05 WARN: JavaSENode update aborted in 2341 ms
00:05 INFO: End deploy result=false-2338
00:05 INFO: Bootstrap completed
03:38 INFO: Stopping Kevoree
03:38 INFO: Stopping node type of node0
03:38 INFO: Kevoree core stopped
03:38 INFO: Stopped.
Terminate batch job (Y/N)? n

Further question:
In
00:03 INFO: Starting node type of node0
I guess that 'node0' is the name of the node. What is the type of the node? (Same message shown while stopping the node).

**Comment by maxleiko** [comment]
Seems like #10 is the same issue.

**Comment by skorsky** [comment]
My pom.xml has
<groupId>org.kevoree.example</groupId>

This was checked out after #10 is solved.

**Comment by skorsky** [comment]
I searched the whole project for 'org.kevoree.sample', but nothing found. I don't know where the values for 
Resolving ............. /packages[org]/packages[kevoree]/packages[sample]/deployUnits[hashcode=,name=helloworld,version=0.0.1-SNAPSHOT]
are configured.

**Comment by skorsky** [comment]
May be it comes from http://registry.kevoree.org/org/kevoree/sample/hashcode=,name=helloworld,version=0.0.1-SNAPSHOT

**Comment by maxleiko** [comment]
I just removed my whole `~/.m2/` directory and made a full `mvn clean install kev:run` and it works.  
Can you try to clean your `.m2` too.  

The type of `node0` is a `JavaNode` type, defined [here](https://github.com/HEADS-project/training/blob/master/2.Kevoree_Basics/1.HelloWorld/java/src/main/kevs/main.kevs) at line 1.  
There is an old version of the TypeDefinition `HelloWorld` and its old DeployUnit `org.kevoree.sample` instead of `org.kevoree.example` remaining on the registry, but it should not cause any problem.

**Comment by kgiannakakisATC** [comment]
I've cleaned my m2 repository and now, no matter what I do, I get this error.

**Comment by skorsky** [comment]
I removed .m2\repository (not the settings.xml) and run 'mvn clean install kev:run'.

But result is the same:
00:00 INFO: Bootstrap Kevoree node : node0, version 5.1.4
00:00 INFO: Resolved 25 typeDefinitions from Kevoree Registry http://registry.kevoree.org/v5/ (JavaNode/5.2.0,JavaNode/5.1.1,JavaNode/5.0.3,JavaNode/5.2.1,JavaNode/5.1.2,JavaNode/5.2.2,JavaNode/5.1.3,JavaNode/5.0.4,JavaNode/5.0.5,JavaNode/5.0.6,JavaNode/5.0.6-SNAPSHOT,JavaNode/5.0.7,JavaNode/5.1.4-SNAPSHOT,JavaNode/5.2.2-SNAPSHOT,JavaNode/5.2.1-SNAPSHOT,JavaNode/5.0.8-SNAPSHOT,JavaNode/5.1.1-SNAPSHOT,JavaNode/5.0.3-SNAPSHOT,JavaNode/5.1.2-SNAPSHOT,JavaNode/5.0.5-SNAPSHOT,JavaNode/5.0.4-SNAPSHOT,JavaNode/5.2.3-SNAPSHOT,JavaNode/5.1.0,JavaNode/5.0.7-SNAPSHOT,HelloWorld/0.0.1-SNAPSHOT)
00:01 WARN: Try to select snapshot in best effort mode for org.kevoree.example.HelloWorld
00:01 INFO: Resolving ............. /packages[org]/packages[kevoree]/packages[library]/packages[java]/deployUnits[hashcode=,name=org.kevoree.library.java.javaNode,version=5.2.2]
00:01 INFO: Resolved in 3ms
00:01 INFO: JavaNode, changing LOG level to INFO
00:01 INFO: Starting node type of node0
00:01 INFO: Resolving ............. /packages[org]/packages[kevoree]/packages[sample]/deployUnits[hashcode=,name=helloworld,version=0.0.1-SNAPSHOT]
00:03 ERROR: No metadata file found for org.kevoree.sample/helloworld/0.0.1-SNAPSHOT
00:03 INFO: Resolved in 2289ms
00:03 ERROR: Unable to resolve /packages[org]/packages[kevoree]/packages[sample]/deployUnits[hashcode=,name=helloworld,version=0.0.1-SNAPSHOT]
00:03 WARN: Error during execution of AddDeployUnit org.kevoree.sample/helloworld/0.0.1-SNAPSHOT/
00:03 WARN: JavaSENode is aborting last update...
00:03 WARN: JavaSENode update aborted in 2309 ms
00:03 INFO: End deploy result=false-2302
00:03 INFO: Bootstrap completed
02:20 INFO: Stopping Kevoree
02:20 INFO: Stopping node type of node0
02:20 INFO: Kevoree core stopped 
02:20 INFO: Stopped.


A full debug log of maven (-X -e) is available, this does not help me.

**Comment by maxleiko** [comment]
Can you give me the model generated in `target/classes/KEV-INF/lib.json`

**Comment by kgiannakakisATC** [comment]
I can't find the lib.json file in java target/classes folder

**Comment by maxleiko** [comment]
It means that the `mvn install` failed. That's why the `mvn kev:run` cannot work properly.

**Comment by maxleiko** [comment]
Just in case, can you give your project zipped ?

**Comment by kgiannakakisATC** [comment]
This is the output from the mvn clean install:

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Kevoree :: helloworld 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ helloworld ---
[INFO] Deleting C:\Users\KGiannakakis\Documents\GitHub\training\2.Kevoree_Basics\1.HelloWorld\java\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ helloworld ---
[WARNING] Using platform encoding (Cp1253 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\KGiannakakis\Documents\GitHub\training\2.Kevoree_Basics\1.HelloWorld\java\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ helloworld ---
[INFO] Compiling 1 source file to C:\Users\KGiannakakis\Documents\GitHub\training\2.Kevoree_Basics\1.HelloWorld\java\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ helloworld ---
[WARNING] Using platform encoding (Cp1253 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\KGiannakakis\Documents\GitHub\training\2.Kevoree_Basics\1.HelloWorld\java\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ helloworld ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ helloworld ---
[INFO] No tests to run.
[INFO]
[INFO] --- org.kevoree.tools.mavenplugin:5.2.1:generate (default) @ helloworld ---
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ helloworld ---
[INFO] Building jar: C:\Users\KGiannakakis\Documents\GitHub\training\2.Kevoree_Basics\1.HelloWorld\java\target\helloworld-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ helloworld ---
[INFO] Installing C:\Users\KGiannakakis\Documents\GitHub\training\2.Kevoree_Basics\1.HelloWorld\java\target\helloworld-0.0.1-SNAPSHOT.jar to C:\Users\KGiannakakis\.m2\repository\org\kevoree\example\helloworld\0.0.1-SNAPSHOT\helloworld-0.0.1-SNAPSHOT.jar
[INFO] Installing C:\Users\KGiannakakis\Documents\GitHub\training\2.Kevoree_Basics\1.HelloWorld\java\pom.xml to C:\Users\KGiannakakis\.m2\repository\org\kevoree\example\helloworld\0.0.1-SNAPSHOT\helloworld-0.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.602 s
[INFO] Finished at: 2015-01-07T13:16:06+02:00
[INFO] Final Memory: 16M/219M
[INFO] ------------------------------------------------------------------------

**Comment by kgiannakakisATC** [comment]
I am attaching the project

**Comment by maxleiko** [comment]
@brice-morin can you confirm that this is working on Windows ? Because, it works on Linux.

**Comment by kehusa** [comment]
@maxime This is the same bug as #17 - Not able to find locally
generated type definitions. I am running on Windows platform

2015-01-07 12:22 GMT+01:00 Maxime Tricoire <notifications@github.com>:
> @brice-morin can you confirm that this is working on Windows ? Because, it
> works on Linux.
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Knut Eilif Husa

Tellu AS
Email: knut.eilif.husa@tellu.no
Mob: (+47) 452 49496
Web: www.tellu.no

**Comment by kehusa** [comment]
@maxleiko I am a bit stuck with this one :-( I do not manage to find my classes in my local maven repo. Are there any ways around it?

00:00 INFO: Bootstrap Kevoree node : chatserver, version 5.2.1
00:00 INFO: Resolved 64 typeDefinitions from Kevoree Registry http://registry.ke
voree.org/v5/ (JavaNode/5.2.0,WSGroup/5.2.1-SNAPSHOT,JavaNode/5.0.3,JavaNode/5.2
.1,JavaNode/5.0.4,JavaNode/5.2.2,JavaNode/5.0.5,WSGroup/5.0.8-SNAPSHOT,JavaNode/
5.0.6,JavaNode/5.0.6-SNAPSHOT,WSGroup/5.0.5-SNAPSHOT,JavaNode/5.0.7,JavaNode/5.1
.4-SNAPSHOT,JavaNode/5.2.2-SNAPSHOT,WSChan/5.2.3-SNAPSHOT,WSMsgBroker/1.0.0,WSMs
gBroker/1.0.1,WSMsgBroker/1.0.2,WSGroup/5.1.2,WSGroup/5.1.3,WSGroup/5.1.4,WSGrou
p/5.1.0,WSGroup/5.1.1,JavaNode/5.1.1-SNAPSHOT,JavaNode/5.0.3-SNAPSHOT,WSChan/5.1
.4-SNAPSHOT,JavaNode/5.1.2-SNAPSHOT,WSGroup/5.2.2-SNAPSHOT,WSGroup/5.0.7,WSGroup
/5.2.3-SNAPSHOT,WSGroup/5.1.2-SNAPSHOT,WSGroup/5.0.7-SNAPSHOT,JavaNode/5.2.3-SNA
PSHOT,JavaNode/5.1.0,JavaNode/5.0.7-SNAPSHOT,JavaNode/5.1.1,JavaNode/5.1.2,JavaN
ode/5.1.3,JavaNode/5.2.1-SNAPSHOT,WSGroup/5.2.1,WSGroup/5.0.3,WSGroup/0.1.0,WSGr
oup/5.2.2,WSGroup/5.0.4,WSGroup/5.0.3-SNAPSHOT,WSGroup/5.0.5,WSGroup/5.0.6,WSCha
n/2.2.3-SNAPSHOT,WSGroup/5.1.1-SNAPSHOT,WSGroup/5.2.0,JavaNode/5.0.8-SNAPSHOT,WS
MsgBroker/0.1.1,WSMsgBroker/0.1.0,WSMsgBroker/0.1.3,WSMsgBroker/0.1.2,WSChan/5.2
.2,WSChan/5.2.1,WSChan/5.2.0,WSChan/5.2.2-SNAPSHOT,WSGroup/5.1.4-SNAPSHOT,JavaNo
de/5.0.5-SNAPSHOT,WSGroup/5.0.4-SNAPSHOT,JavaNode/5.0.4-SNAPSHOT,WSChan/5.2.1-SN
APSHOT)
00:02 WARN: Try to select snapshot in best effort mode for no.tellu.ChatServer
java.lang.Exception: TypeDefinition not found with : no.tellu.ChatServer and ver
sion null in 0 selected
        at org.kevoree.kevscript.util.TypeDefinitionResolver.resolve(TypeDefinit
ionResolver.java:124)
        at org.kevoree.kevscript.KevScriptEngine.interpret(KevScriptEngine.java:
128)
        at org.kevoree.kevscript.KevScriptEngine.interpret(KevScriptEngine.java:
124)
        at org.kevoree.kevscript.KevScriptEngine.interpret(KevScriptEngine.java:
119)
        at org.kevoree.kevscript.KevScriptEngine.executeFromStream(KevScriptEngi
ne.java:58)
        at org.kevoree.bootstrap.Bootstrap.bootstrapFromKevScript(Bootstrap.java
:218)
        at org.kevoree.bootstrap.Bootstrap.bootstrapFromKevScript(Bootstrap.java
:248)
        at org.kevoree.bootstrap.Bootstrap.bootstrapFromFile(Bootstrap.java:337)

        at org.kevoree.bootstrap.Bootstrap.main(Bootstrap.java:85)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.kevoree.microkernel.impl.KevoreeMicroKernelImpl$1.run(KevoreeMicr
oKernelImpl.java:223)

**Comment by maxleiko** [comment]
Yes, Linux, or OSX.

We are working on fixing this issue for Windows.

**Comment by maxleiko** [comment]
Using the new Kevoree 5.2.5 release should fix Windows problems.

**Comment by skorsky** [comment]
yes, Kevoree 5.2.5 fixed this for me.
