### ISSUE TITLE
Same artifact id for all kevoree examples

### ISSUE THREAD

**Issue by kgiannakakisATC** [HEADS-project/training#27]
All kevoree examples share the same artifact id. This is unfortunate, as it makes difficult to import them all in HEADS IDE. You can also can't have more than one of them in your local m2 repository.

**Comment by maxleiko** [comment]
The first 4 Kevoree tutorials are all working on the same `TypeDefinition`, which is `HelloWorld`.  
There is no need to bother reimporting the projects, as you follow the steps of the tutorials, you are supposed to make the 1.HelloWorld evolve in 2., then 3., and finally 4.
