### ISSUE TITLE
Kevoree preference page

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#28]
While searching for the cause of some issue, I saw the Kevoree prference page.
![kevoree preferences](https://cloud.githubusercontent.com/assets/8928699/5662689/d3175d08-973c-11e4-8c05-28e5d3e66f83.png)
When should I configure the version of Kevoree?
The plug-in can retrieve it's version from the OSGi BundleContext class. This would be more consistent since you cannot forget to change it when you update Kevoree.

**Comment by maxleiko** [comment]
This version is used when **you generate a new Kevoree project** from the HEADS IDE, that's all.  
If you've imported a maven project in the HEADS IDE, then this is not used.

**Comment by skorsky** [comment]
New projects should use the installed Kevoree version. May be maven can help to get this version for the pom.xml. 
Currently with setting the preference to 5.1.4, but the installed Kevoree version 5.2.5, I get compile errors since there are API changes. This is hard to find for a newbie.

**Comment by maxleiko** [comment]
@barais

**Comment by barais** [comment]
Ok, I include the plugin in the Kevoree release management. 

So By default, it will be the last stable version. when you create a project.
