### ISSUE TITLE
Tutorial description for the Kevoree Basics Tutorial (JavaScript)

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#29]
The page https://github.com/HEADS-project/training/tree/master/2.Kevoree_Basics describes for the JavaScript projects:

New Kevoree JavaScript Project

    From existing sources: File > New > Project > Kevoree > Kevoree JS Project
        Set the project name
        Set the location of your sources
        Click Finish
    From scratch:
        Follow the first step of the Kevoree JavaScript Tutorial n°1
        Now use the same process as for From existing sources

Questions:
Using the New Kevoree JS Project wizard for the first case
![new kevoree js project](https://cloud.githubusercontent.com/assets/8928699/5662785/22bcfdb2-973e-11e4-9f1b-11d708db6ae1.png), what template should I use?

Does 'Set the location of your sources' mean modify 'Use default location'?

Is node.js a prerequisite?

**Comment by maxleiko** [comment]
Do not check `default location`, but instead, set the location of the actual `kevoree-js` project directory.
Yes, you have to install Node.js manually.

**Comment by skorsky** [comment]
Can you update the Readme.md accordingly?

**Comment by maxleiko** [comment]
b6b2d2c182c9a9192b6322891ddeac76d90429f5
