### ISSUE TITLE
yo kevoree

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#30]
yo kevoree
results in
Error kevoree

You don't seem to have a generator with the name kevoree installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 1 registered generators run yo with the `--help` option.

The installation of generator-kevoree directly befor this command looks OK:
npm install -g generator-kevoree
generator-kevoree@2.2.2 D:\Users\mask\AppData\Roaming\npm\node_modules\generator-kevoree
├── underscore.string@2.3.3
└── yeoman-generator@0.13.4 (dargs@0.1.0, debug@0.7.4, diff@1.0.8, rimraf@2.2.8, text-table@0.1.1, mime@1.2.11, mkdirp@0.3.5, async@0.2.10, isbinaryfile@0.1.9, chalk@0.2.1, shelljs@0.1.4, glob@3.2.11,
 iconv-lite@0.2.11, tar@0.1.20, findup-sync@0.1.3, request@2.25.0, lodash@1.3.1, cheerio@0.12.4, inquirer@0.3.5)

**Comment by maxleiko** [comment]
Can you see `Kevoree` in the list when you only run `yo` as a command-line tool ?

**Comment by maxleiko** [comment]
```txt
$ yo
? 'Allo leiko! What would you like to do? (Use arrow keys)
  Run a generator
❯ Kevoree 
  Angular 
  Jhipster 
  Karma 
  Typescript 
  Webapp 
(Move up and down to reveal more choices)
```

This is what I have. You might have only one result, which is `Kevoree` in your case.

**Comment by maxleiko** [comment]
Actually, it seems like `yo kevoree` is not working anymore with the latest version of `Yeoman`.  

But this works:
```sh
yo kevoree:app
```

**Comment by skorsky** [comment]
OK, that helps.

Now I get
--------------------------------------
I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


'bower' is not recognized as an internal or external command,
operable program or batch file.
npm WARN package.json kevoree-comp-helloworld@0.1.0 No repository field.
/
> kevoree-comp-helloworld@0.1.0 prepublish D:\Users\mask\git\HEADS\training\2.Kevoree_Basics\1.HelloWorld\js
> grunt

'grunt' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! kevoree-comp-helloworld@0.1.0 prepublish: `grunt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kevoree-comp-helloworld@0.1.0 prepublish script.
npm ERR! This is most likely a problem with the kevoree-comp-helloworld package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt
npm ERR! You can get their info via:
npm ERR!     npm owner ls kevoree-comp-helloworld
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\Users\mask\git\HEADS\training\2.Kevoree_Basics\1.HelloWorld\js
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\Users\mask\git\HEADS\training\2.Kevoree_Basics\1.HelloWorld\js\npm-debug.log
npm ERR! not ok code 0
----------------------------
What is 'bower'?
What is 'grunt'?

BTW, yeoman output assumes that the command box has black background. Otherwise not all output is visible.

**Comment by maxleiko** [comment]
You need to install `grunt-cli` to use `kevoree-js`  
See the [tutorial README](https://github.com/HEADS-project/training/tree/master/2.Kevoree_Basics/1.HelloWorld/js#how-to-run-the-project)

**Comment by maxleiko** [comment]
Oh I see, because `yeoman` is triggering `npm install` on the project, `npm` tries to invoke `grunt kevoree`, and this leads to the error.  
I will update the README to tell people to install `grunt-cli` before running `yo kevoree:app`

**Comment by maxleiko** [comment]
458119b528055f0340905b9dbcb72cf0186d9204
