### ISSUE TITLE
Tutorial 4. JAVA - Cannot push new attribute value

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/training#32]
The Tutorial 4 Java is up and running sending messages to printer.
I am trying to change the attribute 'greetMessage' that is sent to printer.
When pushing the new value it does not come through.

In Tutorial 3 there is a printout from the WSGroup when doing a push.
When trying the same in Tutorial 4 there is no printout.

I have tried the same in Tutorial 4 JS version and it works fine changing the attribute

**Comment by maxleiko** [comment]
Looks like the WSGroup in Java has a model-size limitation that prevents it to received the pushed model. I am working on a fix.

**Comment by maxleiko** [comment]
https://github.com/TooTallNate/Java-WebSocket/issues/300

**Comment by maxleiko** [comment]
As a workaround, you can use Firefox to push models.  

> Firefox as canvas issues though. The model drag'n'drop feature will be close to non-existant.

**Comment by brice-morin** [comment]
Yes, indeed, a colleague of mine (@yellowiscool) had the same problem with Java WebSocket. I do not know if he found an alternative lib...

**Comment by yellowiscool** [comment]
I'm not sure if it's the same bug. Mine was TooTallNate/Java-Websocket#209

I haven't been looking for an alternative because I don't use Java on desktop anymore, we rewrote the single Java component using C#. On Android we use koush/AndroidAsync for websockets and it works fine.

**Comment by maxleiko** [comment]
Fixed in the next release (will be 5.2.3) https://github.com/kevoree/kevoree-library/commit/867edcd3800d3dc45f0a2b0b51921a1cbfc25961 using [Undertow](https://github.com/undertow-io/undertow)  

While waiting for the next Kevoree Standard Library release, you can retrieve the source code and compile it as a snapshot locally and then use it in your kevscript as 5.2.3-SNAPSHOT.

**Comment by maxleiko** [comment]
https://github.com/kevoree/kevoree-library/tree/master/java/org.kevoree.library.java.ws

This is the project to compile locally in order to use the WSGroup 5.2.3-SNAPSHOT

**Comment by maxleiko** [comment]
https://github.com/kevoree/kevoree-library/tree/master/java/org.kevoree.library.java.ws

This is the project to compile locally in order to use the WSGroup 5.2.3-SNAPSHOT
