### ISSUE TITLE
'bower' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#39]
Running `yo kevoree`, I get
`'bower' is not recognized as an internal or external command`.

What is 'bower'? Is this needed?

**Comment by maxleiko** [comment]
[bower](http://bower.io/) is a package manager such as `npm` but for Web components. It is run by default by **Yeoman** once your project created. But I bet you can ignore the error message.

Anyway, looks like something like this http://stackoverflow.com/questions/27360710/bower-is-not-recognised-as-an-internal-or-external-command

**Comment by skorsky** [comment]
OK, that helped.
