### ISSUE TITLE
Fatal error: Cannot call method 'findByPath' of null

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#40]
Running step 4 of 2.Kevoree_Basics (JS), I get
`Fatal error: Cannot call method 'findByPath' of null` when stopping the Kevoree runtime with Ctrl-C.

**Comment by maxleiko** [comment]
Step 4 of 2.Kevoree_Basics ? You mean **4.Its_About_Sending_A_Message** ?

**Comment by skorsky** [comment]
Yes.

**Comment by maxleiko** [comment]
Can you send me your project, because I've just tested the **4.** on Linux and Windows and it works.

**Comment by skorsky** [comment]
Trying to reproduce this and isolate it, I found that if
`clearInterval(this.id);` in the stop function causes this if this line is missing.

**Comment by maxleiko** [comment]
Which command-line application do you use ?  
Because it looks like there is none that are trustworthy on Windows :-1:

**Comment by skorsky** [comment]
Following the tutorial readme, I used `grunt kevoree`.

**Comment by maxleiko** [comment]
Not the command you ran, the command-line tool/application you are using.  

Windows default one ?
PowerShell ?
Cygwin ?

**Comment by skorsky** [comment]
Windows default one `cmd`.

**Comment by maxleiko** [comment]
Can you try with PowerShell if you have it ?

**Comment by skorsky** [comment]
Works with PowerShell!

**Comment by maxleiko** [comment]
Tsss, I hate this Operating System.

**Comment by maxleiko** [comment]
How am I supposed to find out why it does not work with the default command-line application ?

**Comment by maxleiko** [comment]
@brice-morin any idea (besides "Windows sucks" because everyone know that) ?

**Comment by brice-morin** [comment]
Well, I do not know. I guess we should at least strongly recommend using PowerShell in the README. Because fixing that issues for any shell on Windows seems like dark magic...

**Comment by skorsky** [comment]
Why not point out, that `clearInterval(this.id);` is necessary in the stop function? If this is called during stop, all is fine.

**Comment by maxleiko** [comment]
`clearInterval(this.id)` is already in the **stop** function call

**Comment by skorsky** [comment]
Yes, in the committed source.

But when I come from exercise 1 (2.Kevoree_Basics/1.HelloWorld/js/), then this line is not in the source of **stop**.

**Comment by maxleiko** [comment]
The hang happens because you have to clear the interval you start in your components **start** functions. If you do not do so, the Kevoree runtime will not be able to properly ends its process while issuing a `Ctrl-c` because it still has some functions that has to run on each delayed interval.

**Comment by maxleiko** [comment]
That was already stated [here](https://github.com/HEADS-project/training/blob/master/2.Kevoree_Basics/4.Its_About_Sending_A_Message/js/README.md#how-to-use-an-output-port)
