### ISSUE TITLE
Is it possible to create an array of input / output ports

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/training#41]
Hi,
In the SINTEF-INST contribution I made a mux/demux handling three ports.
This does not scale...

Is it possible to have an array of input ports to handle a mux with 127 inputs?
Is it possible to have an array of output ports to handle a demux with 127 outputs?

**Comment by maxleiko** [comment]
The only way to do that currently is to add 127 inputs and 127 outputs.

**Comment by maxleiko** [comment]
@sdalgard what is the actual purpose of providing that much inputs/outputs ? I'm interested in the use case, but I don't understand it clearly.

**Comment by sdalgard** [comment]
The use case is connected to the resource constrained devices.
There will be several components on the device that each will have their one-to-one channels that needs to be connected to a host processor.
Between the device and the host processort there will only be one serial link.
All the channels must be multiplexed onto the serial link.
The plan is to make a multiplexer/demultiplexer component that can handle this task.
Since there are many channels to connect between device and host the multiplexer/demultiplexer will need many inputs/outputs.

**Comment by maxleiko** [comment]
- several components
- one-to-one between components and the channel
- one (serial) link between the channel and the host processor

![Mux](http://img4.hostingpics.net/pics/626284sintefinstmuxdemux.png)  

Looks like the components you call TrunkMux and TrunkDemux should be Kevoree channels, no ?

**Comment by sdalgard** [comment]
Hi,
According to discussion with Olivier (presented at the HEADS meeting in Asker) we plan to make the mux/demux as a kev-component. In the attached picture it is integrated into the yellow component named "TRUNK IF". 
It is better to do it as part of a component since the node configuration functionality can integrated with the mux/demux function in the same component.

![capture](https://cloud.githubusercontent.com/assets/2270169/6144542/faeff0a4-b1d8-11e4-8258-726078b04d87.PNG)

**Comment by maxleiko** [comment]
@barais

**Comment by maxleiko** [comment]
There is no way in kevoree v5 to do such thing. The suggestion will be added in for the Kevoree version.
