### ISSUE TITLE
"Compile Java Kevoree" does not create kev-script

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/training#47]
I have started a stepwise approach for training 3.3.
The goal is to test the tool chain before doing more advanced stuff.

1) Generate standalone ThingML code into "Plain Java" using HEADS IDE
    Run the code in ...thingml-gen/java   
    Using: mvn clean package exec:java -Dexec.mainClass=org.thingml.generated.Main
     Ok
2) Generate standalone ThingML code into "Compile Java Kevoree" using HEADS IDE
    Compile the code in ...thingml-gen/java   
     Using:  mvn clean install
     Ok
3) Compile/run the ThingML process inside Kevoree
    Compile the code in ...thingml-gen/java   
     Using:  mvn kev:run
     Fail .....

00:00 INFO: Bootstrap Kevoree node : node0, version 5.2.5
java.io.FileNotFoundException: /home/etostd/heads-co/my-training-fork/3.Wrapping_ThingML_into_Kevoree/3.3_Contrib/SINTEF-INST/thingml-gen/java/src/main/kevs/main.kevs (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.kevoree.bootstrap.Bootstrap.bootstrapFromFile(Bootstrap.java:348)
	at org.kevoree.bootstrap.Bootstrap.main(Bootstrap.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

The problem seems to be that the kev-script not is generated.

FIX:
cd ...thingml-gen/java/src/main
mkdir kevs
Redo steps 2) and 3)
Now it works....:-)

It seems that the kev-script not is generted due to missing directory.

**Comment by brice-morin** [comment]
OK, I will fix that

**Comment by brice-morin** [comment]
OK, I pushed a fix. It should be available in a few minutes on the ThingML update site. If it works, I will also rebuild the whole HEADS IDE.

**Comment by brice-morin** [comment]
Should be fixed now. Re-open the issue if not.
