### ISSUE TITLE
Port names not visible in "editor.kevoree.org" GUI

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/training#48]
When pulling a model from JavaNode generated from ThingML the GUI shows the components and its ports.
![capture](https://cloud.githubusercontent.com/assets/2270169/6164253/95fe0576-b29d-11e4-9c15-d0dc04f395a0.PNG)

Problem: All ports have the same name JavaP. This makes it hard to do connections to a specific port. When pulling model from "sintefboard" I get specific names, it should there be a difference...

The names are available in the kev-script.
![capture2](https://cloud.githubusercontent.com/assets/2270169/6164294/fe611356-b29d-11e4-90c1-2f7e948bfd5c.PNG)

Suggestion: Add the names to the GUI as a "tooltip"

**Comment by sdalgard** [comment]
It seems to be the first 5 characters thas displayed. Maybe a naming convention with significant info first can imporove the situation.

**Comment by maxleiko** [comment]
Yes, I've just added an issue to the editor. I will do something fast.

**Comment by brice-morin** [comment]
Yes, the name generated by ThingML are a bit long, but we have to do it in the general case to avoid possible name clashing (hence the ports have some sort of unique qualified name). Of course I could reverse this qualified name, but that would not be that conventional for a qualified name...

**Comment by maxleiko** [comment]
I've commited a new patch for the editor that gives the full port name if you let your mouse over the port name.

**Comment by maxleiko** [comment]
@sdalgard  @brice-morin It's ok now (might just a cache refresh from your browser, but it's online)
