### ISSUE TITLE
Which channel shall be used for connecting two ThingML ports in a JavaNode?

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/training#49]
I have tried with AsyncBroadcast (nothing happends) and WSChan (error when sending)

**Comment by brice-morin** [comment]
By default, it seems async broadcast works well, but potentially we might want to use other channels (like MQTT in some cases). I do not think we should limit ourselves to one type of channels

**Comment by brice-morin** [comment]
Hmmm... I just read the title of the issue... maybe try sync broadcast... I will retry a sample

**Comment by brice-morin** [comment]
Yes, SyncBroadCast should work. It might be an issue with some other channels when a generated component sends a message right away (possibly before the receiver or the channel is started)

**Comment by maxleiko** [comment]
SyncBroadcast and AsyncBroadcast are **local** channels. They only work within the same node platform.  
If you want multi-node communications, you must either use WSChan or MQTTChannel or create your own.

**Comment by brice-morin** [comment]
yes, I agree. What is the problem with WSChan?

**Comment by maxleiko** [comment]
There is no problem with WSChan :)  
It just requires you to provide a third-party server. You can start one using the **kevoree-js** component **WSMsgBroker**, or (and it is quicker) just install the module locally and globally using:  

```sh
npm i -g wsmsgbroker
```

and then start a server using the command-line:

```sh
wsbrokerserver 9050
```

**Comment by brice-morin** [comment]
@sdalgard can you first try locally (one node) with SyncBroadcast, and then try again with WSChan based on @maxleiko comment?

**Comment by sdalgard** [comment]
They both work now after fixing the generated ThingML code described in #50

**Comment by brice-morin** [comment]
Good!
