### ISSUE TITLE
Warning when running HEADS IDE in Windows

### ISSUE THREAD

**Issue by kgiannakakisATC** [HEADS-project/training#5]
The following warnings appear, when I run Eclipse HEADS IDE for the first time:

![heads_ide_messages](https://cloud.githubusercontent.com/assets/2520223/5409278/b18d5018-81f0-11e4-91e2-42ca8726c92c.png)

It seems to be safe to ignore them, but it would be nice this to be documented.

**Comment by brice-morin** [comment]
A minimal version of the HEADS IDE has been created, which should solve this issue

**Comment by skorsky** [comment]
Hi Brice, where can I find this minimal version of the HEADS IDE? The latest Jenkins build for the HEADS IDE is dated Dec. 16.

**Comment by brice-morin** [comment]
Hi, I will try to find the link and update the doc. But Olivier can probably find it way faster.
________________________________________
De : skorsky [notifications@github.com]
Envoyé : vendredi 16 janvier 2015 13:15
À : HEADS-project/training
Cc : Brice Morin
Objet : Re: [training] Warning when running HEADS IDE in Windows (#5)

Hi Brice, where can I find this minimal version of the HEADS IDE? The latest Jenkins build for the HEADS IDE is dated Dec. 16.

**Comment by brice-morin** [comment]
it is here: http://coreff5.istic.univ-rennes1.fr/jenkins/job/headside/ws/products.minimal/target/products/

**Comment by skorsky** [comment]
That's the link I know. 

Which build solved the issue?
