### ISSUE TITLE
Java compilation message

### ISSUE THREAD

**Issue by kgiannakakisATC** [HEADS-project/training#6]
When compiling to Java the following dialog appears:

![heads_ide_java_message](https://cloud.githubusercontent.com/assets/2520223/5409311/3646f75a-81f1-11e4-862d-c27a5a418a8b.png)

It is difficult to copy-paste the commands from there. Printing them in console would make things easier.

**Comment by brice-morin** [comment]
This message does not appear anymore and source code is generated within the workspace so it should be directly accessible.
