### ISSUE TITLE
New Kevoree Project uses Default Location always

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#68]
I create a new Kevoree Project and uncheck the 'Default Location', choose a folder outside the workspace. But the wizard ignores it. The project files are created at default location.
I use   ThingML 0.6.0.201503030729  org.thingml.eclipse.feature.feature.group   SINTEF-9012
and kevoree-eclipse-plugin 5.1.4

**Comment by maxleiko** [comment]
@barais what's the status on this issue?

**Comment by skorsky** [comment]
It is still an issue. Checked with KevoreeEclipsePluginFeature 5.2.8

**Comment by brice-morin** [comment]
@barais :interrobang:

**Comment by barais** [comment]
I will check

**Comment by barais** [comment]
Ok, I just fix this issue

https://github.com/kevoree/kevoree-eclipse-plugin/commit/1316eabac4e211151a5485d1bc4ab8c8c1d70b59
