### ISSUE TITLE
How to assign a port number in ThingML configuration

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#77]
Is it possible to assign a port number for a port in a ThingML configuration?
If not, how can I configure a port number?

**Comment by brice-morin** [comment]
A port you use internally in a component? Or a port that will then be mapped to a Kevoree port. In the first case, you can declare a property in your thing. Then you can use ```set myinstance.myproperty = xxx``` in your configuration.

**Comment by skorsky** [comment]
It's a port the component should use to connect to the msmsgbroker. so it is mapped to a Kevoree port.

**Comment by brice-morin** [comment]
Then I guess you can set that in a KevScript? We can look later on how we can have that information directly in the ThingML (probably using some annotations)

**Comment by skorsky** [comment]
This means, I modify the generated KevScript?

**Comment by brice-morin** [comment]
For now, yes. Anyway, the generated KevScript is not intented to be final, the service operator should then update it before deployment

**Comment by skorsky** [comment]
OK, thanks for help.
