### ISSUE TITLE
Define several ThingML configurations and decide which one to run

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#78]
Is it possible to define in ThingML configurations like
```
configuration A {
...
}
```
and
```
configuration B {
...
}
```

and then generate Java code, Kevoree Java code and select at runtime which configuration to use with `mvn kev:run`?

This is related to SAG contribution for tutorial 3.

**Comment by brice-morin** [comment]
Outside Eclipse, this would generate two separate Maven projects, then you can ```cd``` into the one you want to ```mvn kev:run```. I have to double check, but inside Eclipse, everything might be "merged" (without any proper merging, more like by chance) into one Maven project within the thingml-gen folder. We should also generate two separate Maven folder in the workspace. I'll check that.

**Comment by skorsky** [comment]
OK, thanks for help.
