### ISSUE TITLE
Tutorial 4.Apama_Basics - "onload" description incorrect

### ISSUE THREAD

**Issue by aliverud** [HEADS-project/training#83]
The 'Developing an Application with MonitorScript' tutorial repeatedly describes 
"Delete the contents of the 'onload' action created in the previous lesson.", this is incorrect as the 'subscribe section' (eg. monitor.subscribe("TemperatureS001");) must remain, otherwise the application will fail at runtime not showing any output.

**Comment by skorsky** [comment]
Hi Anders ( @aliverud ), can you help me where this description is? I found descriptions where ``monitor.subscribe("TemperatureS001");`` is replaced by ``monitor.subscribe("Temperature" + sensor.sensorId);``.

**Comment by aliverud** [comment]
Hi,
The first one is in "Developing an Application with MonitorScript, "Calculate average temperature readings over the last minute".
The next is in "Monitoring Complex Events", "Add a more advanced temperature listener".

Also the description on how to add a "bundle" is incorrect for this version of Apama Workbench. This is in "Making Data Available to Remote Clients" and "Persisting Data (Memory Store)".

**Comment by skorsky** [comment]
Thanks for the hints.
Some of them are fixed with the next Apama version. For the remaining I'll create issues.

Closing issue.
