### ISSUE TITLE
404 Error trying to download Apama

### ISSUE THREAD

**Issue by brice-morin** [HEADS-project/training#84]
Hi,

I tried to download Apama but got a 404 error:
```
An error occurred while reading the resource

Server Error 404

Not found

org.opencms.file.CmsVfsResourceNotFoundException: Error reading the property value for property "secure" of resource "/public/apama/contents/downloads/apama-free-trial/thank-you/index.html".

We are sorry, but the page you were looking for no longer exists.
Please visit http://communities.softwareag.com and choose your preferred Community site.
If you have any questions, please email: technologycommunity@softwareag.com

We will be pleased to help you.


The Communities Team
```

**Comment by skorsky** [comment]
Hi Brice, what is the URL you started with?

**Comment by brice-morin** [comment]
Well, I tried different ones. But this error was for this link : https://www.softwareag.com/corporate/res/download/default.asp  after I logged in and accepted the license. I also tried via https://empower.softwareag.com, but it seems Apama is not available through the installer.

**Comment by skorsky** [comment]
On https://empower.softwareag.com/ Apama is avaliable if you have a license contract. In this case you find the download at  'Home > Products & Documentation > Download Products > Software Download Center '

For the other case I'll contact the community team at technologycommunity@softwareag.com as suggested in the error message.

**Comment by brice-morin** [comment]
OK, thanks. Now I could manage through empower (using IE, as it was doing some strange things with Firefox, for some reasons)

**Comment by skorsky** [comment]
Can we close this issue?

**Comment by skorsky** [comment]
Response from technologycommunity@softwareag.com:

Thank you for notifying us about that.

The page is fixed now. We've tested it and the request for Apama download is working.

Could you please send us the email of the customer, so that we will check if his request was received.
---
Is this still relevant?

**Comment by brice-morin** [comment]
well, I am currently in Apama Studio (from empower), so I guess we can close.
