### ISSUE TITLE
Not possible to download framework from web

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/training#85]
Hi,
The framework download stopps after ~15MB ... :-(
  Same problem for both linux and windows

http://coreff5.istic.univ-rennes1.fr/jenkins/job/headside/ws/products.minimal/target/products/

**Comment by maxleiko** [comment]
@barais any idea why ?

**Comment by brice-morin** [comment]
Yes, same problem on my computer...

**Comment by maxleiko** [comment]
`wget` manages to download btw :)

**Comment by brice-morin** [comment]
bundles are now accessible from a [more reliable/faster mirror](http://headside.gforge.inria.fr/)
