### ISSUE TITLE
Copy .kev file when generating ThingML/nodejs-kevoree

### ISSUE THREAD

**Issue by magnustellu** [HEADS-project/training#90]
Right now we have to copy the content of our .kev file to the generated folder.

As a generic fix, would it be a good idea to solve this by adding a generic annotation or language construct like ```import```? Maybe export?

My idea
```
export "kevs/main.kev"
```
This would copy the referenced file to the generated working directory under the kevs folder. Maybe add a second parameter which explicitly says where to place the file inside the directory.

```
export "kevs/main.kev" "main.kev"
```

Might be useful for other use cases as well.

**Comment by brice-morin** [comment]
You can now use `@kevscript "path/to/my/script.kevs"` on configuration to point to an existing kevscript file, which will be used instead of generating one.
