### ISSUE TITLE
Catch errors when generating from ThingML

### ISSUE THREAD

**Issue by magnustellu** [HEADS-project/training#92]
The IDE has some good syntax and error highlighting, but they are sadly not used by the generator. Unless it is a critical error the generator will not fail. It would be great if the generator would complain and point to the errors.

**Comment by brice-morin** [comment]
The checker should now print a list of warning and errors, pointing to specific files, lines and columns. It might still be some work to report those errors directly in the text editor, but at least it is reasonably easy to trace errors.
