### ISSUE TITLE
Finding a realistic and open-source application using ThingML as a model language

### ISSUE THREAD

**Issue by FeltonXuAtECNU** [HEADS-project/training#98]
I am trying to find a realistic and also open-source application which uses ThingML as a model language.
But there is a few requirement that needs to meet:

1)The scale should not be too big. Usually a project no more than 10 main thignml files(that's the limit for me, maybe something like 5 thingml file is best and the state machine could be somewhat big) because I'm trying to use this one for case study purpose
2)The scenraio should best have something to do with the environment and contain some "uncertainty" and the best is something containing as little advance feature(LIKE CEP) as possible

Thanks a lot in advance!

**Comment by ffleurey** [comment]
None of our industry partners can share the "real-systems" they are building with ThingML at this point so we do not have any ready made system we can share with you which fits your requirements. If you decide to build it yourself we will support you but we cannot build it for you within a reasonable time-frame. Cheers!

**Comment by FeltonXuAtECNU** [comment]
http://thingml.org/pmwiki.php?n=Main.CaseStudy
The case study I want is something like this. All I want is a project that model the real-world situation but doesn't necessarily need it to be used or deployed in real world/industry. Something like a prototype or simplified version of a simple scenario.
