### ISSUE TITLE
Still trying to find an example

### ISSUE THREAD

**Issue by FeltonXuAtECNU** [HEADS-project/training#99]
http://thingml.org/pmwiki.php?n=Main.CaseStudy
The case study I want is something like this. All I want is a project that model the real-world situation but doesn't necessarily need it to be used or deployed in real world/industry. Something like a prototype or simplified version of a simple scenario is what I like because I'm not using thingml to model something useful from scratch. I only use the project in the FIRST STEP (of course, spend almost no time to model some scenraio)and transfer it into another kind of formalism(timed automata) as I posted before to ask for advice. 
The example except for the robot is all toy example(to show how to use a feature mostly).....Also, again I don't want to build something from begining....Is there any available project modelling the real world in some sense.(It doesn't has to be something used in industry)

**Comment by ffleurey** [comment]
Hello, as mentioned several times before, we currently do not have an open case study which which fits your requirements. If you want one you have to make it (either from one of our toy example or from scratch). Again, we can help you build something but we CANNOT build it for you.
